const AuthActionTypes = {
	LOGIN_START: "LOGIN_START",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL",

	REGISTER_START: "REGISTER_START",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAIL: "REGISTER_FAIL",

	UPDATE_CART_START: "UPDATE_CART_START",
	UPDATE_CART_FAIL: "UPDATE_CART_FAIL",
	UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",

	GET_USER_START: "GET_USER_START",
	GET_USER_SUCCESS: "GET_USER_SUCCESS",
	GET_USER_FAIL: "GET_USER_FAIL",

	SET_DELIVERY_FEE: "SET_DELIVERY_FEE",
	SET_DISCOUNT: "SET_DISCOUNT",
	SET_TRANSACTION_FEE: "SET_TRANSACTION_FEE",
};

export default AuthActionTypes;
