const AuthActionTypes = {
	LOGIN_START: "LOGIN_START",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL",

	REGISTER_START: "REGISTER_START",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAIL: "REGISTER_FAIL",

	GET_USER_START: "GET_USER_START",
	GET_USER_SUCCESS: "GET_USER_SUCCESS",
	GET_USER_FAIL: "GET_USER_FAIL",
};

export default AuthActionTypes;
