const CategoryActionTypes = {
	GET_CATEGORIES_START: "GET_CATEGORIES_START",
	GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
	GET_CATEGORIES_FAIL: "GET_CATEGORIES_FAIL",

	SET_CURRENT_CATEGORY: "SET_CURRENT_CATEGORY",
};

export default CategoryActionTypes;
