const MerchantActionTypes = {
	GET_MERCHANTS_START: "GET_MERCHANTS_START",
	GET_MERCHANTS_SUCCESS: "GET_MERCHANTS_SUCCESS",
	GET_MERCHANTS_FAIL: "GET_MERCHANTS_FAIL",

	GET_ONE_MERCHANT_START: "GET_ONE_MERCHANT_START",
	GET_ONE_MERCHANT_SUCCESS: "GET_ONE_MERCHANT_SUCCESS",
	GET_ONE_MERCHANT_FAIL: "GET_ONE_MERCHANT_FAIL",

	SET_CURRENT_MERCHANT: "SET_CURRENT_MERCHANT",
};

export default MerchantActionTypes;
