const ProductActionTypes = {
	GET_PRODUCTS_START: "GET_PRODUCTS_START",
	GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
	GET_PRODUCTS_FAIL: "GET_PRODUCTS_FAIL",

	GET_SALE_PRODUCTS_START: "GET_SALE_PRODUCTS_START",
	GET_SALE_PRODUCTS_SUCCESS: "GET_SALE_PRODUCTS_SUCCESS",
	GET_SALE_PRODUCTS_FAIL: "GET_SALE_PRODUCTS_FAIL",

	SEARCH_PRODUCT: "SEARCH_PRODUCT",
	FILTER_PRODUCT: "FILTER_PRODUCT",
	SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",
};

export default ProductActionTypes;
