const ProductActionTypes = {
	GET_PRODUCTS_START: "GET_PRODUCTS_START",
	GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
	GET_PRODUCTS_FAIL: "GET_PRODUCTS_FAIL",

	GET_NEW_PRODUCTS_START: "GET_NEW_PRODUCTS_START",
	GET_NEW_PRODUCTS_SUCCESS: "GET_NEW_PRODUCTS_SUCCESS",
	GET_NEW_PRODUCTS_FAIL: "GET_NEW_PRODUCTS_FAIL",

	GET_PRODUCTS_BY_MERCHANT_START: "GET_PRODUCTS_BY_MERCHANT_START",
	GET_PRODUCTS_BY_MERCHANT_SUCCESS: "GET_PRODUCTS_BY_MERCHANT_SUCCESS",
	GET_PRODUCTS_BY_MERCHANT_FAIL: "GET_PRODUCTS_BY_MERCHANT_FAIL",

	GET_SALE_PRODUCTS_START: "GET_SALE_PRODUCTS_START",
	GET_SALE_PRODUCTS_SUCCESS: "GET_SALE_PRODUCTS_SUCCESS",
	GET_SALE_PRODUCTS_FAIL: "GET_SALE_PRODUCTS_FAIL",

	SEARCH_PRODUCT_START: "SEARCH_PRODUCT_START",
	SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
	SEARCH_PRODUCT_FAIL: "SEARCH_PRODUCT_FAIL",

	FILTER_PRODUCT: "FILTER_PRODUCT",
	SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",
};

export default ProductActionTypes;
